name: enterprise
description: Corporate Application

version: 0.3.1+3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter
  path: ^1.6.4
  image_picker: ^0.6.3+1
  liquid_pull_to_refresh: ^1.1.1
  cupertino_icons: ^0.1.2
  shared_preferences: 0.5.6+1
  http: ^0.12.0+2
  sqflite: ^1.2.0
  path_provider: ^1.6.0
  font_awesome_flutter: ^8.5.0
  date_format: ^1.0.8
  flutter_speed_dial: ^1.2.5
  charts_flutter: ^0.8.1
  flutter_slidable: ^0.4.9
  file_picker: ^1.4.3+2
  flutter_nfc_reader:
    git:
      url: git://github.com/matteocrippa/flutter-nfc-reader.git
      ref: master
  firebase_messaging: ^6.0.9
  package_info: 0.4.0+14
  url_launcher: 5.4.2
  local_auth: 0.6.1+3

dev_dependenfcies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

module:
  androidX: true