name: enterprise
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  shared_preferences: ^0.4.3
  http: ^0.12.0+2
  sqflite: any
  path_provider: any
  font_awesome_flutter: any
  date_format: ^1.0.8
  flutter_speed_dial: ^1.2.5
  charts_flutter: ^0.8.1
#  cloud_firestore:
  file_picker: ^1.4.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter

assets:
  - assets/

flutter:
  uses-material-design: true

module:
  androidX: true